networks:
  inetwork:

services:
  xpra:
    image: kohs100/docker-xpra:latest
    ports:
      - 8081:8080
    environment:
      - TZ=Asia/Tokyo
      # - DISPLAY=:0.0
      # - PORT=8080
      # - WIDTH=1920
      # - HEIGHT=1080
      # - DEPTH=24
      # - BITPERPIXEL=32
    restart: unless-stopped
    networks:
      - inetwork
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: [
      "--bell=no",
      "--notifications=no",
      "--audio=no",
      "--file-transfer=no",
      "--webcam=no",
      "--bandwidth-limit=10Mbps"
    ]

  test:
    image: kohs100/docker-xpra-client:latest
    environment:
     - DISPLAY=xpra:0.0
    networks:
      - inetwork
    depends_on:
      xpra:
        condition: service_healthy